#!usr/bin/python3
# -*- coding: utf-8 -*-

#4-1 披萨
loved_pizzas=['Durian pizza', 'Mango pizza', 'Seafood pizza', 'Turkey pizza', 'Beef Cheese pizza']
for pizza in loved_pizzas:
    print('i like '+pizza+'.')
print('i really love pizza!')

#4-2 动物
animal_types=['Dog', 'cat', 'rabbit', 'duck']
for animal in animal_types:
    print('A '+animal.title()+' would make a great pet.')
print('Any of these animals would make a great pet!')

#4-3 数到20
for i in range(1,21):
    print(i)

#4-4 输出整数
million_list=range(1, 1000001)
'''
for i in million_list:
    print(i)
'''
if min(million_list)==1 and max(million_list)==1000000:
    print('True')
else:
    print('False')
print(sum(million_list))

odd_list=range(1, 20, 2)
for odd in odd_list:
    print(odd)

third_list=[x for x in range(3, 31) if x%3==0]
for third in third_list:
    print(third_list)

cube_list=[x**3 for x in range(11)]
for number in cube_list:
    print(number)

cube_lamb=lambda x: x**3
cube=[]
for i in range(1,11):
    cube.append(cube_lamb(i))
print(cube)
